[[plugins]] # vim plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # IDE
repo = 'Shougo/unite.vim'

[[plugins]] # color scheme
repo = 'tomasr/molokai'

[[plugins]] # intent guide
repo = 'nathanaelkane/vim-indent-guides'
