###############################
## Vim General Plugin Repo
###############################

[[plugins]] 
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'rking/ag.vim'

###############################
## スキーマ
###############################
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'davidhalter/jedi-vim'

###############################
## コード補完
###############################
[[plugins]]
repo = 'Shougo/neocomplcache.vim'

[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'

[[plugins]]
repo = 'rsense/rsense'

###############################
## 静的解析
###############################
[[plugins]]
repo = 'scrooloose/syntastic'

###############################
## ドキュメント参照
###############################
[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'

###############################
## メソットジャンプ
###############################
[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tsukkee/unite-tag'

###############################
## タグ閉じ
###############################
[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

###############################
## 自動セッション
###############################
[[plugins]]
repo = 'xolox/vim-session'

[[plugins]]
repo = 'xolox/vim-misc'

###############################
## VIEW
###############################

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-haml'

###############################
## Ruby, Rails Plugin Repo
###############################

[[plugins]]
repo = 'shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

###############################
## Front develop
###############################
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'AtsushiM/sass-compile.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'statianzo/vim-jade'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'ianks/vim-tsx'

[[plugins]]
repo = 'leafgarland/typescript-vim'

###############################
## Markdown
###############################
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

###############################
## Git Plugin Repo
###############################

[[plugins]]
repo = 'tpope/vim-fugitive'

###############################
## Node JS
###############################

[[plugins]]
repo = 'heavenshell/vim-jsdoc'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'elzr/vim-json'
