
###############################
## Vim General Plugin Repo
###############################

[[plugins]] # vim plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # IDE
repo = 'Shougo/unite.vim'

[[plugins]] # color scheme
repo = 'tomasr/molokai'

[[plugins]] # indent guide
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # tree
repo = 'scrooloose/nerdtree'

###############################
## Ruby, Rails Plugin Repo
###############################

[[plugins]] # neosnippet
repo = 'Shougo/neosnippet'

[[plugins]] # rails
repo = 'tpope/vim-rails'

[[plugins]] # endwise
repo = 'tpope/vim-endwise'
