
###############################
## Vim General Plugin Repo
###############################

[[plugins]] # vim plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # IDE
repo = 'Shougo/unite.vim'

[[plugins]] # IDE option
repo = 'Shougo/neomru.vim'

[[plugins]] # color scheme
repo = 'tomasr/molokai'

[[plugins]] # indent guide
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # tree
repo = 'scrooloose/nerdtree'

[[plugins]] # nerdtree share
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]] # ctrlp
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]] # endwise
repo = 'tpope/vim-endwise'

[[plugins]] # tcomment_vim
repo = 'tomtom/tcomment_vim'

[[plugins]] # statu bar
repo = 'vim-airline/vim-airline'

[[plugins]] # autoclose
repo = 'Townk/vim-autoclose'

###############################
## Ruby, Rails Plugin Repo
###############################

[[plugins]] # neosnippet
repo = 'Shougo/neosnippet'

[[plugins]] # snippet
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # rails
repo = 'tpope/vim-rails'

###############################
## Git Plugin Repo
###############################

[[plugins]] # git
repo = 'tpope/vim-fugitive'
